DROP TABLE IF EXISTS Marketinguru CASCADE;
DROP TABLE IF EXISTS Query CASCADE;
DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS QueryCustomer CASCADE;
DROP TABLE IF EXISTS Product CASCADE;
DROP TABLE IF EXISTS Subscription CASCADE;
