DROP TABLE IF EXISTS Guru CASCADE;
DROP TABLE IF EXISTS Query CASCADE;
DROP TABLE IF EXISTS Customer CASCADE;
DROP TABLE IF EXISTS QueryCustomer CASCADE;
DROP TABLE IF EXISTS Consent CASCADE;
DROP TABLE IF EXISTS CustomerConsent CASCADE;
